<?php

use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('events')->delete();
        
        \DB::table('events')->insert(array (
            0 => 
            array (
                'event_id' => 1,
                'datetime' => '2015-01-24 16:00:00',
                'name' => 'リスアニ！LIVE-5 -SATURDAY STAGE-',
                'venue_name' => '日本武道館',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:35:17',
                'updated_at' => '2019-11-22 05:35:17',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'event_id' => 2,
                'datetime' => '2014-10-02 19:30:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage」',
            'venue_name' => 'TSUTAYA O-WEST (Shibuya O-WEST)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:38:10',
                'updated_at' => '2019-11-22 05:38:10',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'event_id' => 3,
                'datetime' => '2015-02-11 18:00:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage vol.Ⅱ」',
            'venue_name' => '恵比寿LIQUIDROOM(リキッドルーム)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:41:00',
                'updated_at' => '2019-11-22 05:41:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'event_id' => 4,
                'datetime' => '2015-10-04 17:00:00',
                'name' => 'リスアニ！CIRCUIT Vol.07',
                'venue_name' => '新宿BLAZE',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:50:37',
                'updated_at' => '2019-11-22 05:50:37',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'event_id' => 5,
                'datetime' => '2015-10-16 18:00:00',
            'name' => 'ichigo presents 「ごちヤデ(ФωФ)！」',
                'venue_name' => '心斎橋BIGCAT',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:52:20',
                'updated_at' => '2019-11-22 05:52:20',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'event_id' => 6,
                'datetime' => '2015-10-18 17:00:00',
            'name' => 'ichigo presents 「ごちバイ(ФωФ)！」',
                'venue_name' => '福岡DRUM LOGOS',
            'summary' => '岸田教団&THE明星ロケッツ 分島花音 GARNiDELiA メイリア(水橋舞/GARNiDELiA) 三澤紗千香',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:54:07',
                'updated_at' => '2019-11-22 05:54:07',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'event_id' => 7,
                'datetime' => '2015-11-07 18:00:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage vol.Ⅲ」',
                'venue_name' => '豊洲PIT',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:56:15',
                'updated_at' => '2019-11-22 05:56:15',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'event_id' => 8,
                'datetime' => '2015-12-20 17:00:00',
                'name' => 'Anison-R presents Special Xmas LIVE 2015!!',
                'venue_name' => '札幌KRAPS HALL',
            'summary' => '綾野ましろ GARNiDELiA メイリア(水橋舞/GARNiDELiA) MICHI',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 05:59:41',
                'updated_at' => '2019-11-22 05:59:41',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'event_id' => 9,
                'datetime' => '2016-03-13 13:00:00',
                'name' => 'GARNiDELiA メジャーデビュー2周年パーティー ～GARNiDELiA 初のファンミーティング♪♪～第1部',
                'venue_name' => '乃木坂スクエア',
                'summary' => '1部 13:00～14:30
2部 16:30～18:00',
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:07:52',
                'updated_at' => '2019-11-22 06:07:52',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'event_id' => 10,
                'datetime' => '2016-03-13 16:30:00',
                'name' => 'GARNiDELiA メジャーデビュー2周年パーティー ～GARNiDELiA 初のファンミーティング♪♪～第2部',
                'venue_name' => '乃木坂スクエア',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:09:14',
                'updated_at' => '2019-11-22 06:09:14',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'event_id' => 11,
                'datetime' => '2016-03-12 16:00:00',
                'name' => 'FANJ Premium Live 2016-Spring-',
                'venue_name' => '京都FANJ',
            'summary' => 'メイリア(水橋舞/GARNiDELiA) GARNiDELiA 黒崎真音 鈴木このみ',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:12:29',
                'updated_at' => '2019-11-22 06:12:29',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'event_id' => 12,
                'datetime' => '2016-03-21 17:30:00',
                'name' => 'サンクチュアリ with ZIP-FM SCK サブカルキングダム',
                'venue_name' => '名古屋CLUB QUATTRO',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) livetune＋ やのあんな(livetune+) みみめめMIMI タカオユキ Yun*chi',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:15:02',
                'updated_at' => '2019-11-22 06:15:02',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'event_id' => 13,
                'datetime' => '2016-05-03 18:00:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage vol.Ⅳ」',
            'venue_name' => 'マイナビBLITZ赤坂(赤坂BLITZ)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:16:58',
                'updated_at' => '2019-11-22 06:16:58',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'event_id' => 14,
                'datetime' => '2016-08-07 18:00:00',
                'name' => 'galaxia1周年記念LIVE',
                'venue_name' => 'TwinBox AKIHABARA',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:22:37',
                'updated_at' => '2019-11-22 06:22:37',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'event_id' => 15,
                'datetime' => '2016-12-10 17:30:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage vol.Ⅴ」大阪公演',
                'venue_name' => '心斎橋BIGCAT',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:24:29',
                'updated_at' => '2019-11-22 06:24:29',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'event_id' => 16,
                'datetime' => '2016-12-17 18:00:00',
                'name' => 'GARNiDELiAワンマンライブ「stellacage vol.Ⅴ」東京公演',
            'venue_name' => '品川プリンスホテル ステラボール(StellarBall)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:26:51',
                'updated_at' => '2019-11-22 06:26:51',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'event_id' => 17,
                'datetime' => '2017-03-05 12:30:00',
                'name' => 'GARNiDELiA メジャーデビュー3周年パーティー in サンリオピューロランド ~星のささやき~ <第１部>',
                'venue_name' => 'サンリオピューロランド',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:30:45',
                'updated_at' => '2019-11-22 06:30:45',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'event_id' => 18,
                'datetime' => '2017-03-05 15:30:00',
                'name' => 'GARNiDELiA メジャーデビュー3周年パーティー in サンリオピューロランド ~星のささやき~ <第２部>',
                'venue_name' => 'サンリオピューロランド',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:32:11',
                'updated_at' => '2019-11-22 06:32:11',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'event_id' => 19,
                'datetime' => '2017-02-11 13:30:00',
                'name' => '名古屋スクールオブミュージック＆ダンス専門学校「トークショー＆ミニライブ」',
                'venue_name' => '名古屋スクールオブミュージック&ダンス専門学校',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:34:07',
                'updated_at' => '2019-11-22 06:34:07',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'event_id' => 20,
                'datetime' => '2016-08-07 14:30:00',
                'name' => 'GARNiDELiA「約束 -Promise code-」発売記念 スペシャルパーティー',
                'venue_name' => 'TwinBox AKIHABARA',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:36:18',
                'updated_at' => '2019-11-22 06:36:18',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'event_id' => 21,
                'datetime' => '2017-08-09 14:30:00',
                'name' => 'お台場みんなの夢大陸2017 めざましライブ アニソンパラダイス',
                'venue_name' => 'お台場・青海特設会場',
            'summary' => '綾野ましろ 影山ヒロノブ GARNiDELiA きただにひろし CHiCO(CHiCO with HoneyWorks) どうぶつビスケッツ PPP(Penguins Performance Project) 尾崎由香 本宮佳奈 小野早稀 佐々木未来 根本流風 田村響華 相羽あいな 築田行子 メイリア(水橋舞/GARNiDELiA) Ayasa',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:38:20',
                'updated_at' => '2019-11-22 06:38:20',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'event_id' => 22,
                'datetime' => '2017-10-01 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2017 東京公演',
                'venue_name' => 'Zepp Tokyo',
            'summary' => 'みうめ(COJIRASE THE TRIP) 仮面ライアー217',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:39:33',
                'updated_at' => '2019-11-22 06:39:33',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'event_id' => 23,
                'datetime' => '2017-04-16 18:00:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜愛知公演＞',
            'venue_name' => '新栄APOLLO BASE(旧 アポロシアター)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:44:37',
                'updated_at' => '2019-11-22 06:44:37',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'event_id' => 24,
                'datetime' => '2017-05-03 18:00:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜大阪公演＞',
                'venue_name' => '梅田CLUB QUATTRO',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:50:19',
                'updated_at' => '2019-11-22 06:50:19',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'event_id' => 25,
                'datetime' => '2017-05-13 18:00:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜宮城公演＞',
            'venue_name' => '仙台CLUB JUNK BOX(SCJB)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 06:56:26',
                'updated_at' => '2019-11-22 06:56:26',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'event_id' => 26,
                'datetime' => '2017-05-20 19:30:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜上海公演＞',
            'venue_name' => '万代南梦宫上海文化中心 梦想剧场 (バンダイナムコ上海文化センター 夢想劇場)',
            'summary' => '仮面ライアー217 みうめ(COJIRASE THE TRIP)',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 07:00:45',
                'updated_at' => '2019-11-22 07:00:45',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'event_id' => 27,
                'datetime' => '2017-06-03 18:00:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜福岡公演＞',
            'venue_name' => 'Early Believers(アーリービリーバーズ)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 07:02:51',
                'updated_at' => '2019-11-22 07:02:51',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'event_id' => 28,
                'datetime' => '2017-06-11 18:00:00',
                'name' => 'GARNiDELiA stellacage TOUR 2017 ~Cry Out~ ＜東京公演＞',
            'venue_name' => 'ディファ有明(閉館)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 07:04:50',
                'updated_at' => '2019-11-22 07:04:50',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'event_id' => 29,
                'datetime' => '2016-12-23 14:00:00',
                'name' => 'GARNiDELiA「Violet Cry」発売記念予約イベント 阪急西宮ガーデンズ',
                'venue_name' => '阪急西宮ガーデンズ 4Fスカイガーデン 木の葉のステージ',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 07:08:13',
                'updated_at' => '2019-11-22 07:08:13',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'event_id' => 30,
                'datetime' => '2018-01-27 16:00:00',
                'name' => 'リスアニ！LIVE 2018 SATURDAY STAGE',
                'venue_name' => '日本武道館',
            'summary' => 'ClariS GARNiDELiA メイリア(水橋舞/GARNiDELiA) OLDCODEX 鈴木達央 YORKE. May\'n TrySail 夏川椎菜 雨宮天 麻倉もも CHiCO(CHiCO with HoneyWorks) 早見沙織 冨田明宏 黒須克彦 村田一弘 岩瀬聡志 山本陽介 大串友紀',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 07:10:48',
                'updated_at' => '2019-11-22 07:10:48',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'event_id' => 31,
                'datetime' => '2016-06-11 17:00:00',
                'name' => 'ANIMAGICA 2016 大阪公演',
                'venue_name' => '心斎橋BIGCAT',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) SCREEN mode ピコ ChouCho うみくん(UMI☆KUUN) 林勇 太田雅友',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 22:56:56',
                'updated_at' => '2019-11-22 22:56:56',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'event_id' => 32,
                'datetime' => '2017-01-28 16:00:00',
                'name' => 'リスアニ！LIVE 2017 SATURDAY STAGE',
                'venue_name' => '日本武道館',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:01:01',
                'updated_at' => '2019-11-22 23:01:01',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'event_id' => 33,
                'datetime' => '2019-10-05 16:30:00',
                'name' => 'Anime Rave Festival 第2章',
            'venue_name' => 'Zepp DiverCity (TOKYO)',
                'summary' => NULL,
                'tag_text' => 'アニレヴ',
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:05:26',
                'updated_at' => '2019-11-22 23:05:26',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'event_id' => 34,
                'datetime' => '2016-03-05 16:00:00',
                'name' => 'Ｖ３新人オーディション 21th',
            'venue_name' => '福岡SKALA ESPACIO(スカラエスパシオ)',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) 瀧川ありさ XOX(キスハグキス)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:09:15',
                'updated_at' => '2019-11-22 23:09:15',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'event_id' => 35,
                'datetime' => '2018-03-24 16:30:00',
                'name' => 'AnimeJapan 2018 1日目【WHITE-5】SACRA MUSIC LIVE STAGE',
            'venue_name' => '東京ビッグサイト(東京国際展示場)',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) LiSA TrySail 麻倉もも 雨宮天 夏川椎菜',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:11:28',
                'updated_at' => '2019-11-22 23:11:28',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'event_id' => 36,
                'datetime' => '2017-01-07 13:00:00',
                'name' => 'あいちポップカルチャーフェスティバル2017 GARNiDELiAミニライブ',
            'venue_name' => '愛・地球博記念公園(モリコロパーク)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:15:13',
                'updated_at' => '2019-11-22 23:15:13',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'event_id' => 37,
                'datetime' => '2018-09-08 10:00:00',
                'name' => 'チャイナフェスティバル 2018',
            'venue_name' => '代々木公園野外ステージ(代々木公園野外音楽堂)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:26:43',
                'updated_at' => '2019-11-22 23:26:43',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'event_id' => 38,
                'datetime' => '2016-08-19 15:30:00',
                'name' => 'AFAThailand 2016 Featured Anime showcase: Qualidea Code',
                'venue_name' => 'Siam Paragon',
            'summary' => '福原綾香 メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:29:14',
                'updated_at' => '2019-11-22 23:29:14',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'event_id' => 39,
                'datetime' => '2017-08-18 19:00:00',
                'name' => 'EGOIST Greeting Tour 2017「E / A」 名古屋公演',
                'venue_name' => 'Zepp Nagoya',
            'summary' => 'EGOIST chelly GARNiDELiA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:32:55',
                'updated_at' => '2019-11-22 23:32:55',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'event_id' => 40,
                'datetime' => '2018-12-02 14:00:00',
                'name' => 'C3AFA SINGAPORE 2018 3日目 I LOVE ANISONG CONCERT Artist Autograph GARNiDELiA',
                'venue_name' => 'Suntec International Convention and Exhibition Centre',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:37:54',
                'updated_at' => '2019-11-22 23:37:54',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'event_id' => 41,
                'datetime' => '2017-03-10 19:00:00',
                'name' => 'Anisong Fantasy Live 2017 香港',
                'venue_name' => 'The Queen Elizabeth Stadium',
            'summary' => '春奈るな Kalafina 瀧川ありさ GARNiDELiA Aimer ELISA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:41:49',
                'updated_at' => '2019-11-22 23:41:49',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'event_id' => 42,
                'datetime' => '2018-11-25 17:30:00',
                'name' => '第6回 Act Against AIDS 2018 in SENDAI',
                'venue_name' => '仙台Rensa',
            'summary' => 'FLOW GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) 閖上太鼓保存会',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:49:49',
                'updated_at' => '2019-11-22 23:49:49',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'event_id' => 43,
                'datetime' => '2017-11-26 13:30:00',
                'name' => '『アニメガタリズ』ファン感謝イベント「阿佐ヶ谷家クリスマスパーティーへようこそ☆」①',
                'venue_name' => '豊洲PIT',
            'summary' => '本渡楓 千本木彩花 東城日沙子 寺島惇太 伊藤節生 高橋李依 水瀬いのり 西明日香 高森奈津美 高木美佑 財満健太 加隈亜衣 古川慎 近藤浩徳 GARNiDELiA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:53:52',
                'updated_at' => '2019-11-22 23:53:52',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'event_id' => 44,
                'datetime' => '2017-11-26 18:00:00',
                'name' => '『アニメガタリズ』ファン感謝イベント「阿佐ヶ谷家クリスマスパーティーへようこそ☆」②',
                'venue_name' => '豊洲PIT',
            'summary' => '本渡楓 千本木彩花 東城日沙子 寺島惇太 伊藤節生 高橋李依 水瀬いのり 西明日香 高森奈津美 高木美佑 財満健太 加隈亜衣 古川慎 近藤浩徳 GARNiDELiA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:55:27',
                'updated_at' => '2019-11-22 23:55:27',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'event_id' => 45,
                'datetime' => '2018-09-29 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 東京公演【追加公演】',
            'venue_name' => 'Zepp DiverCity (TOKYO)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:56:49',
                'updated_at' => '2019-11-22 23:56:49',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'event_id' => 46,
                'datetime' => '2017-03-18 19:00:00',
                'name' => 'Anisong Fantasy Live 2017 シンガポール',
                'venue_name' => 'Megabox Event Hall @ Bigbox',
            'summary' => '春奈るな Kalafina 瀧川ありさ GARNiDELiA Aimer ELISA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-22 23:59:43',
                'updated_at' => '2019-11-22 23:59:43',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'event_id' => 47,
                'datetime' => '2017-11-23 14:00:00',
                'name' => 'ANIMAX MUSIX 2017 YOKOHAMA',
                'venue_name' => '横浜アリーナ',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:03:14',
                'updated_at' => '2019-11-23 00:03:14',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'event_id' => 48,
                'datetime' => '2015-07-12 14:00:00',
                'name' => '音霊 OTODAMA SEA STUDIO 2015 ～だから海って特別な場所なのかな 2015’～',
            'venue_name' => '音霊OTODAMA SEA STUDIO(由比ガ浜)',
            'summary' => '綾野ましろ GARNiDELiA メイリア(水橋舞/GARNiDELiA) 榊原ゆい 佐藤聡美 春奈るな fhána みみめめMIMI タカオユキ',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:05:16',
                'updated_at' => '2019-11-23 00:05:16',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'event_id' => 49,
                'datetime' => '2015-04-25 11:00:00',
                'name' => '超音楽祭2015 DAY1',
                'venue_name' => '幕張メッセ 国際展示場ホール',
            'summary' => 'アルスマグナ 小林幸子 ZAQ Juice=Juice SUPER☆GiRLS でんぱ組.inc 古坂大魔王 undervar 黒崎真音 9nine 大石昌良(オーイシマサヨシ) RAB(リアルアキバボーイズ)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:13:02',
                'updated_at' => '2019-11-23 00:13:02',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'event_id' => 50,
                'datetime' => '2017-03-26 16:30:00',
                'name' => 'AnimeJapan 2017 2日目 REDステージ Program 6「劇場版 魔法科高校の劣等生 星を呼ぶ少女」スペシャルステージ',
            'venue_name' => '東京ビッグサイト(東京国際展示場)',
            'summary' => '中村悠一 早見沙織 内山夕実 佐藤聡美 日笠陽子 GARNiDELiA メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:15:47',
                'updated_at' => '2019-11-23 00:15:47',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'event_id' => 51,
                'datetime' => '2014-04-27 11:00:00',
                'name' => '超音楽祭2014 ～超会議3～ DAY2',
                'venue_name' => '幕張メッセ 国際展示場ホール',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:20:30',
                'updated_at' => '2019-11-23 00:20:30',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'event_id' => 52,
                'datetime' => '2018-07-07 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 埼玉公演',
                'venue_name' => 'HEAVEN\'S ROCKさいたま新都心VJ-3',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:31:49',
                'updated_at' => '2019-11-23 00:31:49',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'event_id' => 53,
                'datetime' => '2018-07-08 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 茨城公演',
                'venue_name' => '水戸LIGHT HOUSE',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 00:36:06',
                'updated_at' => '2019-11-23 00:36:06',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'event_id' => 54,
                'datetime' => '2018-07-14 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 千葉公演',
            'venue_name' => '柏PALOOZA(パルーザ)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 13:45:25',
                'updated_at' => '2019-11-23 13:45:25',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'event_id' => 55,
                'datetime' => '2018-07-15 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 長野公演',
                'venue_name' => '長野CLUB JUNK BOX',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 13:48:13',
                'updated_at' => '2019-11-23 13:48:13',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'event_id' => 56,
                'datetime' => '2018-08-04 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 京都公演',
            'venue_name' => 'KYOTO MUSE(京都MUSE)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 13:52:18',
                'updated_at' => '2019-11-23 13:52:18',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'event_id' => 57,
                'datetime' => '2018-08-05 17:30:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 兵庫公演',
                'venue_name' => '神戸VARIT.',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 13:57:38',
                'updated_at' => '2019-11-23 13:57:38',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'event_id' => 58,
                'datetime' => '2018-08-11 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 香川公演',
            'venue_name' => '高松DIME(ダイム)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 13:59:58',
                'updated_at' => '2019-11-23 13:59:58',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'event_id' => 59,
                'datetime' => '2018-08-12 17:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 広島公演',
                'venue_name' => '広島CAVE-BE',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:04:20',
                'updated_at' => '2019-11-23 14:04:20',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'event_id' => 60,
                'datetime' => '2018-08-18 18:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 岩手公演',
                'venue_name' => '盛岡CLUB CHANGE WAVE',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:08:11',
                'updated_at' => '2019-11-23 14:08:11',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'event_id' => 61,
                'datetime' => '2018-08-19 17:00:00',
                'name' => 'GARNiDELiA stellacage Live House Tour 2018 "glow" 秋田公演',
                'venue_name' => '秋田Club SWINDLE',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:10:19',
                'updated_at' => '2019-11-23 14:10:19',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'event_id' => 62,
                'datetime' => '2018-12-16 18:00:00',
                'name' => 'リスアニ！LIVE TAIWAN 2018［SUNDAY STAGE］',
                'venue_name' => '台灣大學綜合體育館',
            'summary' => '井口裕香 Machico 中島愛 GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) ASCA(大倉明日香) 冨田明宏 シュアン',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:18:49',
                'updated_at' => '2019-11-23 14:18:49',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'event_id' => 63,
                'datetime' => '2018-05-25 19:00:00',
                'name' => 'CIVILIAN presents INCIDENT619 vol.13',
            'venue_name' => '梅田バナナホール(BananaHall)',
            'summary' => 'GARNiDELiA CIVILIAN メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:32:04',
                'updated_at' => '2019-11-23 14:32:04',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'event_id' => 64,
                'datetime' => '2018-04-07 17:30:00',
                'name' => 'GARNiDELiA stellacage Tour 2018 大阪公演',
            'venue_name' => '梅田バナナホール(BananaHall)',
                'summary' => 'ガルニデ 3と4 Arrow of LoveとSPEED STARの順番が曖昧',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:47:08',
                'updated_at' => '2019-11-23 14:56:17',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'event_id' => 65,
                'datetime' => '2018-04-14 17:30:00',
                'name' => 'GARNiDELiA stellacage Tour 2018 愛知公演',
            'venue_name' => '名古屋Electric Lady Land(E.L.L.)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 14:57:44',
                'updated_at' => '2019-11-23 14:57:44',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'event_id' => 66,
                'datetime' => '2018-04-29 18:00:00',
                'name' => 'GARNiDELiA stellacage Tour 2018 東京公演',
                'venue_name' => '中野サンプラザホール',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 15:01:26',
                'updated_at' => '2019-11-23 15:01:26',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'event_id' => 67,
                'datetime' => '2018-05-05 19:30:00',
                'name' => 'GARNiDELiA stellacage Tour 2018 in Hong Kong',
                'venue_name' => 'Music Zone@E-Max',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 15:05:49',
                'updated_at' => '2019-11-23 15:05:49',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'event_id' => 68,
                'datetime' => '2016-12-03 17:00:00',
                'name' => 'リスアニ！LIVE TAIWAN [SATURDAY STAGE]',
            'venue_name' => '台北國際會議中心 (TICC / Taipei International Convention Center)',
            'summary' => '内田真礼 GARNiDELiA メイリア(水橋舞/GARNiDELiA) 黒崎真音 TrySail 雨宮天 麻倉もも 夏川椎菜 洲崎綾 田所あずさ KiRiKo(桐子) 冨田明宏',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 15:15:16',
                'updated_at' => '2019-11-23 15:15:21',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'event_id' => 69,
                'datetime' => '2019-03-21 17:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 東京公演',
            'venue_name' => 'マイナビBLITZ赤坂(赤坂BLITZ)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-23 15:21:48',
                'updated_at' => '2019-11-23 15:21:48',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'event_id' => 70,
                'datetime' => '2019-03-30 19:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 香港公演',
            'venue_name' => 'MacPherson Stadium 麥花臣場館(マクファーソンスタジアム)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 02:32:30',
                'updated_at' => '2019-11-24 02:32:30',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'event_id' => 71,
                'datetime' => '2019-04-06 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 上海公演',
            'venue_name' => '万代南梦宫上海文化中心 梦想剧场 (バンダイナムコ上海文化センター 夢想劇場)',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) みうめ(COJIRASE THE TRIP) 仮面ライアー217',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 02:39:30',
                'updated_at' => '2019-11-24 02:39:30',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'event_id' => 72,
                'datetime' => '2019-04-07 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 北京公演',
                'venue_name' => '北京 糖果TANGO',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) みうめ(COJIRASE THE TRIP) 仮面ライアー217',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 02:50:44',
                'updated_at' => '2019-11-24 02:50:44',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'event_id' => 73,
                'datetime' => '2019-04-13 19:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 新加坡公演',
                'venue_name' => 'Zepp@BIGBOX Singapore',
                'summary' => 'シンガポール公演',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 02:54:56',
                'updated_at' => '2019-11-24 02:54:56',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'event_id' => 74,
                'datetime' => '2019-05-11 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 重慶公演',
                'venue_name' => '重庆寅派动力',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) みうめ(COJIRASE THE TRIP) 仮面ライアー217',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 02:57:45',
                'updated_at' => '2019-11-24 02:57:45',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'event_id' => 75,
                'datetime' => '2019-05-25 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 深圳公演',
                'venue_name' => 'A8 LiveHouse',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) みうめ(COJIRASE THE TRIP) 仮面ライアー217',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:01:36',
                'updated_at' => '2019-11-24 03:01:36',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'event_id' => 76,
                'datetime' => '2019-06-01 19:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" in Taipei',
                'venue_name' => 'Legacy Taipei',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:03:54',
                'updated_at' => '2019-11-24 03:03:54',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'event_id' => 77,
                'datetime' => '2019-06-23 17:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 北海道公演',
            'venue_name' => '札幌PENNY LANE24(ペニーレーン24)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:07:15',
                'updated_at' => '2019-11-24 03:07:15',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'event_id' => 78,
                'datetime' => '2019-06-30 17:30:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 大阪公演',
                'venue_name' => 'なんばHatch',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:11:46',
                'updated_at' => '2019-11-24 03:11:46',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'event_id' => 79,
                'datetime' => '2019-07-07 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 愛知公演',
            'venue_name' => '名古屋ダイアモンドホール(DIAMOND HALL)',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:14:25',
                'updated_at' => '2019-11-24 03:14:25',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'event_id' => 80,
                'datetime' => '2019-07-27 17:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 福岡公演',
                'venue_name' => '福岡DRUM LOGOS',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:17:21',
                'updated_at' => '2019-11-24 03:17:21',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'event_id' => 81,
                'datetime' => '2019-08-03 18:00:00',
                'name' => 'GARNiDELiA stellacage Asia Tour 2019 "響喜乱舞" 埼玉公演',
                'venue_name' => '大宮ソニックシティ 大ホール',
                'summary' => 'みうめ、仮面ライアー217、SLH、ATY
ダブルアンコールの記述に対応できていない',
                'tag_text' => NULL,
                'event_type' => 0,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:21:15',
                'updated_at' => '2019-11-24 03:24:10',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'event_id' => 82,
                'datetime' => '2019-01-27 18:00:00',
                'name' => 'リスアニ！LIVE 2019 SUNDAY STAGE',
                'venue_name' => '日本武道館',
            'summary' => 'アイドルマスターミリオンライブ！ミリオンスターズ 山崎はるか 伊藤美来 上田麗奈 駒形友梨 GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) KOTOKO CHiCO(CHiCO with HoneyWorks) HoneyWorks 宮野真守 JUNNA 鈴木みのり halca 冨田明宏 岩瀬聡志 黒須克彦 大串友紀 村田一弘 山本陽介 中西(HoneyWorks/HoneyMonster) 宇都圭輝(HoneyWorks/ex.cake)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:29:34',
                'updated_at' => '2019-11-24 03:29:40',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'event_id' => 83,
                'datetime' => '2019-05-18 16:00:00',
                'name' => 'SACRA MUSIC FES.2019–NEW GENERATION- DAY1',
                'venue_name' => '幕張メッセ イベントホール',
            'summary' => 'ASCA(大倉明日香) 綾野ましろ =LOVE 大谷映美里 大場花菜 音嶋莉沙 齋藤樹愛羅 佐々木舞香 佐竹のん乃 髙松瞳 瀧脇笙古 野口衣織 諸橋沙夏 山本杏奈 輝夜月 GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) ClariS 斉藤壮馬 澤野弘之(SawanoHiroyuki[nZk]) 三月のパンタシア スピラ・スピカ TrySail 夏川椎菜 雨宮天 麻倉もも halca PENGUIN RESEARCH 生田鷹司 堀江晶太 神田ジョン 新保恵大 柴﨑洋輔 ReoNa 黒須克彦 EGOIST 藍井エイル 吉田尚記 DJ MarGenal Gemie(R!N/坂本理沙) Tielle 幹葉 ますだ(スピラ・スピカ) 寺西裕二',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:31:29',
                'updated_at' => '2019-11-24 03:31:29',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'event_id' => 84,
                'datetime' => '2019-05-19 15:00:00',
                'name' => 'SACRA MUSIC FES.2019–NEW GENERATION- DAY2',
                'venue_name' => '幕張メッセ イベントホール',
            'summary' => 'ASCA(大倉明日香) 綾野ましろ =LOVE 大谷映美里 大場花菜 音嶋莉沙 齋藤樹愛羅 齊藤なぎさ 佐々木舞香 佐竹のん乃 髙松瞳 瀧脇笙古 野口衣織 諸橋沙夏 山本杏奈 輝夜月 GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) ClariS 斉藤壮馬 澤野弘之(SawanoHiroyuki[nZk]) 三月のパンタシア スピラ・スピカ TrySail 夏川椎菜 雨宮天 麻倉もも halca PENGUIN RESEARCH 生田鷹司 堀江晶太 神田ジョン 新保恵大 柴﨑洋輔 ReoNa 黒須克彦 DJ MarGenal LiSA 藍井エイル Gemie(R!N/坂本理沙) Tielle EGOIST 幹葉 ますだ(スピラ・スピカ) 寺西裕二',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:33:31',
                'updated_at' => '2019-11-24 03:33:31',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'event_id' => 85,
                'datetime' => '2017-11-05 16:00:00',
                'name' => '神奈川工科大学「幾徳祭」GARNiDELiA LIVE',
                'venue_name' => '神奈川工科大学',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 03:40:30',
                'updated_at' => '2019-11-24 03:40:30',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'event_id' => 86,
                'datetime' => '2018-03-04 14:30:00',
                'name' => 'GARNiDELiA モバイルファンクラブ galaxia限定イベント ＜GARNiDELiAメジャーデビュー4周年パーティー　～歌舞伎町の星～＞',
                'venue_name' => '新宿RUIDO.K4',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 1,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 12:20:45',
                'updated_at' => '2019-11-24 12:20:45',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'event_id' => 87,
                'datetime' => '2018-06-08 20:00:00',
                'name' => 'Garnidelia A-Kon Concert',
                'venue_name' => 'Fort Worth Convention Center Arena',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 12:24:27',
                'updated_at' => '2019-11-24 12:24:27',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'event_id' => 88,
                'datetime' => '2017-05-14 18:00:00',
                'name' => 'COMCHA FES 2017 in 野音',
                'venue_name' => '日比谷野外大音楽堂',
            'summary' => '井口裕香 櫻井孝宏 水瀬いのり May\'n GARNiDELiA メイリア(水橋舞/GARNiDELiA) 鈴村健一 下野紘 和島あみ',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 12:30:45',
                'updated_at' => '2019-11-24 12:30:45',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'event_id' => 89,
                'datetime' => '2015-11-01 12:00:00',
                'name' => '東京電機大学『旭祭』GARNiDELiA TALK & LiVE',
                'venue_name' => '東京電機大学 東京千住キャンパス',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 12:34:50',
                'updated_at' => '2019-11-24 12:34:50',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'event_id' => 90,
                'datetime' => '2019-10-25 18:30:00',
                'name' => 'GARNiDELiA presents HALLOWEEN MiRACLE WONDER PARTY',
                'venue_name' => '豊洲PIT',
            'summary' => 'GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) アナタシア kradness COJIRASE THE TRIP みうめ(COJIRASE THE TRIP) 仮面ライアー217 シェアロックホームズ センラ mia MeseMoa. やなぎなぎ',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 12:45:59',
                'updated_at' => '2019-11-24 12:45:59',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'event_id' => 91,
                'datetime' => '2019-01-19 14:00:00',
                'name' => 'ANIMAX MUSIX 2019 OSAKA supported by ひかりTV',
                'venue_name' => '大阪城ホール',
            'summary' => 'i☆Ris 山北早紀 芹澤優 茜屋日海夏 若井友希 久保田未夢 澁谷梓希 伊藤美来 大橋彩香 小倉唯 GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) SCREEN mode 林勇 太田雅友 鈴木みのり 寺島拓篤 TRUE(唐沢美帆) nano(ナノ) fripSide 南條愛乃 八木沼悟志 Poppin\'Party 愛美(寺川愛美) 大塚紗英 西本りみ Machico 三森すずこ 山崎はるか Run Girls, Run! 林鼓子 森嶋優花 厚木那奈美 gal\'up! (ウマ娘 プリティーダービー) 木村千咲 首藤志奈 高柳知葉 前田玲奈',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 21:24:58',
                'updated_at' => '2019-11-24 21:24:58',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'event_id' => 92,
                'datetime' => '2018-08-24 16:00:00',
                'name' => 'Animelo Summer Live 2018 “OK!” 1日目',
                'venue_name' => 'さいたまスーパーアリーナ',
            'summary' => 'Aqours 伊波杏樹 逢田梨香子 諏訪ななか 小宮有紗 斉藤朱夏 小林愛香 高槻かなこ 鈴木愛奈 降幡愛 亜咲花 いとうかなこ 伊藤美来 Wake Up, Girls! 吉岡茉祐 永野愛理 田中美海 青山吉能 山下七海 奥野香耶 高木美佑 内田彩 OLDCODEX 鈴木達央 YORKE. GARNiDELiA メイリア(水橋舞/GARNiDELiA) toku(GARNiDELiA) 黒崎真音 Zwei Megu(Zwei) Ayumu(Zwei) DearDream 石原壮馬 溝口琢矢 富田健太郎 太田将熙 正木郁 Do As Infinity 伴都美子 中島愛 春奈るな Poppin\'Party 愛美(寺川愛美) 大塚紗英 西本りみ 大橋彩香 伊藤彩沙 MYTH&ROID Tom-H@ck KIHOW(MYTH&ROID) 三森すずこ 山崎エリイ(Erii) 楠木ともり 藍井エイル ぐんまちゃん 山崎淳 村上聖 山内”masshoi”優 松尾洋一 今井隼 毛利泰士 FIRE HORNS',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 21:34:51',
                'updated_at' => '2019-11-24 21:34:51',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'event_id' => 93,
                'datetime' => '2018-02-03 14:00:00',
                'name' => 'GARNiDELiA「Error」発売記念イベント（ラ チッタデッラ中央噴水広場）',
            'venue_name' => '川崎ラ チッタデッラ(LA CITTADELLA) 中央噴水広場',
                'summary' => NULL,
                'tag_text' => NULL,
                'event_type' => 3,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 21:38:30',
                'updated_at' => '2019-11-24 21:38:30',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'event_id' => 94,
                'datetime' => '2017-11-23 14:00:00',
                'name' => 'ANIMAX MUSIX 2017 YOKOHAMA',
                'venue_name' => '横浜アリーナ',
            'summary' => 'angela atsuko(angela) KATSU(angela) 井口裕香 Wake Up, Girls! 田中美海 高木美佑 奥野香耶 永野愛理 青山吉能 吉岡茉祐 山下七海 GARNiDELiA メイリア(水橋舞/GARNiDELiA) ClariS JUNNA 茅原実里 東山奈央 TRUE(唐沢美帆) 羽多野渉 Fo\'xTails ミルキィホームズ 三森すずこ 徳井青空 佐々木未来 橘田いずみ やなぎなぎ Luce Twinkle Wink☆ 宇佐美幸乃 板山紗織 桧垣果穂 深沢紗希 錦織めぐみ fripSide 南條愛乃 八木沼悟志 桃井はるこ every♥ing! 木戸衣吹 山崎エリイ(Erii) 成海ひいな(ex.奏真ひいな)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 21:40:42',
                'updated_at' => '2019-11-24 21:40:42',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'event_id' => 95,
                'datetime' => '2017-05-27 16:00:00',
                'name' => 'SME MUSIC THEATER 2017 1日目',
                'venue_name' => 'さいたまスーパーアリーナ',
            'summary' => '綾野ましろ Aimer ELISA Kalafina GARNiDELiA ClariS 澤野弘之(SawanoHiroyuki[nZk]) CHiCO(CHiCO with HoneyWorks) TrySail 春奈るな FLOW LiSA 麻倉もも 雨宮天 夏川椎菜 メイリア(水橋舞/GARNiDELiA) さユり(酸欠少女さユり) 三月のパンタシア シド 高垣彩陽 戸松遥 mizuki(瑞葵) Gemie(R!N/坂本理沙) Tielle EGOIST T.M.Revolution 西川貴教 黒須克彦',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 21:57:40',
                'updated_at' => '2019-11-24 21:57:40',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'event_id' => 96,
                'datetime' => '2017-05-28 16:00:00',
                'name' => 'SME MUSIC THEATER 2017 2日目',
                'venue_name' => 'さいたまスーパーアリーナ',
            'summary' => '綾野ましろ Aimer ELISA Kalafina GARNiDELiA ClariS 澤野弘之(SawanoHiroyuki[nZk]) CHiCO(CHiCO with HoneyWorks) TrySail 春奈るな FLOW LiSA 麻倉もも 雨宮天 夏川椎菜 メイリア(水橋舞/GARNiDELiA) さユり(酸欠少女さユり) 三月のパンタシア シド 高垣彩陽 戸松遥 Tielle mizuki(瑞葵) Gemie(R!N/坂本理沙) 西川貴教 T.M.Revolution EGOIST 黒須克彦',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:00:45',
                'updated_at' => '2019-11-24 22:00:45',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'event_id' => 97,
                'datetime' => '2017-01-14 14:00:00',
                'name' => 'ANIMAX MUSIX 2017 OSAKA',
                'venue_name' => '大阪城ホール',
            'summary' => 'i☆Ris 山北早紀 芹澤優 久保田未夢 茜屋日海夏 若井友希 澁谷梓希 Wake Up, Girls! 吉岡茉祐 永野愛理 田中美海 青山吉能 山下七海 奥野香耶 高木美佑 every♥ing! 木戸衣吹 山崎エリイ(Erii) 大橋彩香 OxT 大石昌良(オーイシマサヨシ) Tom-H@ck GARNiDELiA メイリア(水橋舞/GARNiDELiA) KOTOKO 下地紫野 鈴木このみ 鈴村健一 茅原実里 EXiNA(西沢幸奏) fripSide 南條愛乃 八木沼悟志 水瀬いのり 栗林みな実(Minami) ミルキィホームズ 三森すずこ 徳井青空 佐々木未来 橘田いずみ 春奈るな',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:02:48',
                'updated_at' => '2019-11-24 22:02:48',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'event_id' => 98,
                'datetime' => '2016-10-14 17:30:00',
                'name' => 'スポーツ・オブ・ハート・ミュージックフェス2016 1日目',
                'venue_name' => '国立代々木競技場第一体育館',
            'summary' => 'こぶしファクトリー アップアップガールズ(仮) 分島花音 みみめめMIMI 飯田里穂 スフィア 豊崎愛生 戸松遥 高垣彩陽 寿美菜子 鈴木このみ Pile Ray(歌手) 吉川友 GARNiDELiA メイリア(水橋舞/GARNiDELiA) AKINO with bless4 タカオユキ チャオ ベッラ チンクエッティ(THE ポッシボー) 鷲崎健 アンジュルム(ex.スマイレージ) 9nine SUPER☆GiRLS Asterisk -アスタリスク- from 2ねん8くみ 吉井香奈恵 村田寛奈 佐武宇綺 西脇彩華 佐藤綾乃 仙石みなみ 新井愛瞳 関根梓 佐保明梨 森咲樹 古川小夏',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:15:07',
                'updated_at' => '2019-11-24 22:15:07',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'event_id' => 99,
                'datetime' => '2015-10-24 18:00:00',
                'name' => 'めざましテレビPRESENTS T-SPOOK 2015 1日目',
                'venue_name' => 'お台場・青海特設会場',
            'summary' => 'きゃりーぱみゅぱみゅ ももいろクローバーZ 西内まりや May J. angela atsuko(angela) ケラケラ HoneyWorks CHiCO(CHiCO with HoneyWorks) 超特急 女王蜂 南波志帆 GARNiDELiA メイリア(水橋舞/GARNiDELiA) TEMPURA KIDZ fumika アルスマグナ 花岡なつみ アキシブproject 有安杏果 佐々木彩夏 高城れに 百田夏菜子 玉井詩織',
                'tag_text' => NULL,
                'event_type' => 4,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:17:15',
                'updated_at' => '2019-11-24 22:17:15',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'event_id' => 100,
                'datetime' => '2015-09-12 16:00:00',
                'name' => 'きたまえ↑札幌☆マンガ・アニメフェスティバル アニソン野外ライブ「アニフォレ」【１日目】',
                'venue_name' => '札幌芸術の森 野外ステージ',
            'summary' => '藍井エイル angela カスタマイZ(カスタマイズ) GARNiDELiA 田所あずさ 水木一郎 DJ和 きただにひろし 藤井孝太郎 前田幸(マエダミユキ)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:18:59',
                'updated_at' => '2019-11-24 22:20:22',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'event_id' => 101,
                'datetime' => '2015-08-29 16:00:00',
                'name' => 'Animelo Summer Live 2015 THE GATE 2日目',
                'venue_name' => 'さいたまスーパーアリーナ',
            'summary' => 'アイドルマスターシンデレラガールズ i☆Ris angela 川田まみ GARNiDELiA SCREEN mode スフィア 宮野真守 ミルキィホームズ 三森すずこ 徳井青空 橘田いずみ 佐々木未来 分島花音 大橋彩香 福原綾香 原紗友里 黒沢ともよ 大空直美 内田真礼 山本希望 青木瑠璃子 洲崎綾 五十嵐裕美 高森奈津美 大坪由佳 松嵜麗 佳村はるか 林勇 太田雅友 戸松遥 豊崎愛生 高垣彩陽 寿美菜子 芹澤優 山北早紀 茜屋日海夏 若井友希 久保田未夢 澁谷梓希 今井麻美 内田彩 Pile 蒼井翔太 七森中☆ごらく部 三上枝織 津田美波 大久保瑠美 ChouCho カスタマイZ(カスタマイズ) 3年E組サマ担 渕上舞 岡本信彦 逢坂良太 田中美海 山谷祥生 南條愛乃 佐々木恵梨 天誅ガールズ fripSide Marty Friedman 深沢紗希 板山紗織 錦織めぐみ 桧垣果穂 宇佐美幸乃 海保えりか 八木沼悟志 メイリア(水橋舞/GARNiDELiA)',
                'tag_text' => NULL,
                'event_type' => 2,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:21:44',
                'updated_at' => '2019-11-24 22:21:44',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'event_id' => 102,
                'datetime' => '2015-02-15 16:00:00',
                'name' => 'Coming Next 2015',
                'venue_name' => 'NHKホール',
            'summary' => 'GARNiDELiA カスタマイZ(カスタマイズ) ぽこた 乙女新党',
                'tag_text' => NULL,
                'event_type' => 4,
                'edit_user_id' => 1,
                'created_at' => '2019-11-24 22:23:36',
                'updated_at' => '2019-11-24 22:23:36',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}